[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PRIVATE_TARGET = "server"
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "your_key"
  # Add other env vars as needed

[[plugins]]
  package = "@netlify/plugin-nextjs"